name: stale

on:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          days-before-stale: 60
          days-before-close: 7
          exempt-issue-labels: "in progress"
          exempt-pr-labels: "in progress"
          labels-to-remove-when-unstale: "stale"
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale. If not updated, it will be closed in 7 days."
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale. If not updated, it will be closed in 7 days."
